name: Push 2.1 ED to gh-pages branch

# Reference documentation: https://docs.github.com/en/actions/reference

# See https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestbranchestags
on:
  push:
    branches: [WCAG-2.1]

jobs:
  main:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          ref: WCAG-2.1
      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: _site
          token: ${{ secrets.W3CGRUNTBOT_TOKEN }}
      - name: Build
        run: |
          cp guidelines/guidelines.css guidelines/relative-luminance.html _site/guidelines
          curl https://labs.w3.org/spec-generator/?type=respec"&"url=https://raw.githack.com/$GITHUB_REPOSITORY/WCAG-2.1/guidelines/index.html -o _site/guidelines/index.html -f  --retry 3
      - name: Push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          repository: _site
          branch: gh-pages
          commit_user_name: w3cgruntbot
          commit_user_email: 87540780+w3cgruntbot@users.noreply.github.com
          commit_author: "w3cgruntbot <87540780+w3cgruntbot@users.noreply.github.com>"
          commit_message: ":robot: Deploy to GitHub Pages: ${{ github.sha }} from branch ${{ github.ref }}"
          skip_fetch: true
          skip_checkout: true
